"""The metric catalogue, generated from the adapters rather than written by hand.

A package with ~150 columns needs a document saying what each one is, which engine produces
it, in what unit and over what range. Hand-written, that document drifts out of sync within
weeks — and a catalogue that lies is worse than no catalogue, because it is trusted.

So it is generated from the same :class:`MetricSpec` declarations the schema is assembled
from, and CI fails when the committed copy differs from the generated one (R-16). An
out-of-date catalogue is a build failure, not a chore.
"""

from __future__ import annotations

from collections.abc import Sequence

from .contract import Adapter
from .core import comparable_keys
from .schema import (
    DEFAULT_DIVERGENCE_THRESHOLD,
    IDENTITY_COLUMNS,
    SCHEMA_VERSION,
    column_name,
    delta_column,
    divergent_column,
)

_HEADER = """<!-- GENERATED by dca.catalogue — do not edit by hand.
     Regenerate with: dca catalogue --write docs/metric-catalogue.md
     CI regenerates this and fails if the result differs from what is committed (R-16). -->

# Metric catalogue

Schema version **{schema_version}**.

Every metric column is named `{{metric}}__{{engine}}`. The bare metric name is deliberately
absent from the schema: radon and lizard disagree about Halstead volume by a median factor
of 14 on ordinary open-source Python, so a column called `halstead_volume` would invite the
reader to assume there is one answer when there demonstrably is not (ADR-0004).

Identity columns: {identity}.
"""

_DIVERGENCE_INTRO = """
## Divergence columns

For every metric that more than one engine computes, the schema carries two extra columns:

* `<metric>__delta_ratio` — the largest reading over the smallest, among non-null readings.
* `<metric>__divergent` — true when that ratio exceeds {threshold:.0%}, **or** when one
  engine reports zero and another does not.

The zero case has no ratio and is the strongest disagreement there is: one engine says the
quantity is absent, another says it is present. On generated code this is the common case
for Halstead, and it is the most informative signal in the table.
"""


def generate(adapters: Sequence[Adapter]) -> str:
    """Render the catalogue for a set of adapters."""
    lines = [
        _HEADER.format(
            schema_version=SCHEMA_VERSION,
            identity=", ".join(f"`{c}`" for c in IDENTITY_COLUMNS),
        )
    ]

    for adapter in adapters:
        specs = adapter.declared_metrics
        lines.append(f"\n## `{adapter.name}`\n")
        # Deliberately no version here. The catalogue describes the *schema*, which is the
        # same everywhere; engine versions are environment-specific and belong in the
        # per-run provenance envelope. Embedding them made this document regenerate
        # differently on every interpreter, so the drift check failed on Python 3.11 and
        # 3.13 while passing on 3.12 — a document that cannot be stable cannot be checked.
        lines.append(f"Integration: **{adapter.path}**.\n")
        lines.append("| Column | Granularity | Unit | Type | Range | Null means | Description |")
        lines.append("|---|---|---|---|---|---|---|")
        for spec in specs:
            low, high = spec.valid_range
            span = (
                f"{'' if low is None else low}–{'' if high is None else high}"
                if (low, high) != (None, None)
                else "—"
            )
            lines.append(
                f"| `{column_name(spec.key, adapter.name)}` "
                f"| {spec.granularity.value} | {spec.unit} | {spec.dtype} | {span} "
                f"| {spec.null_semantics.value} | {spec.description} |"
            )

    comparable = comparable_keys(adapters)
    if comparable:
        lines.append(_DIVERGENCE_INTRO.format(threshold=DEFAULT_DIVERGENCE_THRESHOLD))
        lines.append("| Metric | Engines compared | Ratio column | Flag column |")
        lines.append("|---|---|---|---|")
        for key in sorted(comparable):
            engines = ", ".join(f"`{e}`" for e in sorted(comparable[key]))
            lines.append(
                f"| `{key}` | {engines} | `{delta_column(key)}` | `{divergent_column(key)}` |"
            )

    return "\n".join(lines) + "\n"
